# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Deploy github page

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "npm"
      - run: |
          git config user.name "JugaYa Bot"
          git config user.email "<>"
      - run: npm ci
      - run: npm run deploy
